#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PinnedHeaderExpandableList.Net.Resource", IsApplication=true)]

namespace PinnedHeaderExpandableList.Net
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f04000e
			public const int Grey = 2130968590;
			
			// aapt resource value: 0x7f040009
			public const int LightGray = 2130968585;
			
			// aapt resource value: 0x7f040008
			public const int alpha_00 = 2130968584;
			
			// aapt resource value: 0x7f04000c
			public const int background = 2130968588;
			
			// aapt resource value: 0x7f040005
			public const int black = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int blue = 2130968580;
			
			// aapt resource value: 0x7f040007
			public const int light_orange = 2130968583;
			
			// aapt resource value: 0x7f040001
			public const int lucensy = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int orange = 2130968579;
			
			// aapt resource value: 0x7f04000b
			public const int red = 2130968587;
			
			// aapt resource value: 0x7f04000a
			public const int trans = 2130968586;
			
			// aapt resource value: 0x7f040002
			public const int translucency = 2130968578;
			
			// aapt resource value: 0x7f040006
			public const int transparent = 2130968582;
			
			// aapt resource value: 0x7f04000d
			public const int transparent_background = 2130968589;
			
			// aapt resource value: 0x7f040000
			public const int white = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int child_bg = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int collapse = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int expanded = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_action_search = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_launcher = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Icon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int selector_group = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int selector_item = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080002
			public const int address = 2131230722;
			
			// aapt resource value: 0x7f080001
			public const int age = 2131230721;
			
			// aapt resource value: 0x7f080004
			public const int button1 = 2131230724;
			
			// aapt resource value: 0x7f08000a
			public const int expandablelist = 2131230730;
			
			// aapt resource value: 0x7f080005
			public const int group = 2131230725;
			
			// aapt resource value: 0x7f080003
			public const int image = 2131230723;
			
			// aapt resource value: 0x7f080008
			public const int imageView1 = 2131230728;
			
			// aapt resource value: 0x7f08000b
			public const int menu_settings = 2131230731;
			
			// aapt resource value: 0x7f080000
			public const int name = 2131230720;
			
			// aapt resource value: 0x7f080009
			public const int sticky_content = 2131230729;
			
			// aapt resource value: 0x7f080007
			public const int sticky_header = 2131230727;
			
			// aapt resource value: 0x7f080006
			public const int sticky_layout = 2131230726;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int child = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int group = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int main = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int main = 2131165184;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int hello_world = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int menu_settings = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int title_activity_main = 2131034115;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int AppTheme = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
